// File generated by FlutterFire CLI / Firebase setup.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1c38Cki4lkjeP_SF8UmcEAMk9eUicEJI',
    appId: '1:929793604727:web:2344e11b208ad0ac121a72',
    messagingSenderId: '929793604727',
    projectId: 'sportsphere-45964',
    authDomain: 'sportsphere-45964.firebaseapp.com',
    storageBucket: 'sportsphere-45964.firebasestorage.app',
    measurementId: 'G-C7XTQ42FB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1c38Cki4lkjeP_SF8UmcEAMk9eUicEJI',
    appId: '1:929793604727:android:2344e11b208ad0ac121a72',
    messagingSenderId: '929793604727',
    projectId: 'sportsphere-45964',
    storageBucket: 'sportsphere-45964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1c38Cki4lkjeP_SF8UmcEAMk9eUicEJI',
    appId: '1:929793604727:ios:2344e11b208ad0ac121a72',
    messagingSenderId: '929793604727',
    projectId: 'sportsphere-45964',
    storageBucket: 'sportsphere-45964.firebasestorage.app',
    iosBundleId: 'com.example.sportsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1c38Cki4lkjeP_SF8UmcEAMk9eUicEJI',
    appId: '1:929793604727:ios:2344e11b208ad0ac121a72',
    messagingSenderId: '929793604727',
    projectId: 'sportsphere-45964',
    storageBucket: 'sportsphere-45964.firebasestorage.app',
    iosBundleId: 'com.example.sportsphere',
  );
}
